apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/skulesh01/Ceres.git
    targetRevision: main
    path: deployment/gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: redmine
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
